---
ID: "81a3ef86-f304-4831-a77b-e2320bab59f3"
Parent: "46eb8483-4586-449f-b31a-2c53ba1b7dba"
Template: "46eb8483-4586-449f-b31a-2c53ba1b7dba"
Path: /sitecore/templates/Project/QuadBike/BaseTemplate/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0c4c9552-d838-4f1b-b177-735bfb2be0e1"
      Hint: Title
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191007T140809Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
